NUMPY


In [6]:
import numpy as np
np.__version__

'1.26.4'

In [7]:
a=[1,2,3,4,5,6]
print(a)

[1, 2, 3, 4, 5, 6]


In [8]:
type(a)

list

In [9]:
arr=np.array(a)
print(arr)

[1 2 3 4 5 6]


In [10]:
type(arr)

numpy.ndarray

arange()---- takes maximum of 3 arguments,if single arguument is given it is second argument that follows (n-1)  and 3rd parameter is skip count.1st argument should be less than second argument

In [12]:
b=np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
b=np.arange(3.3)
print(b)

[0. 1. 2. 3.]


In [14]:
b=np.arange(1,10)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
b=np.arange(0,101,5)
b

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [16]:
np.arange(-23,23)

array([-23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12, -11,
       -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19,  20,  21,  22])

zeros() =to create matrix with 0 by default it takes float data type tto use it in int data type use dtype=int
zeros(5) used to created 1d matrix
zerox(x,y) used  to created xy matrix where x is rows and y is columns

In [61]:
k=np.zeros(5)
k

array([0., 0., 0., 0., 0.])

In [63]:
k=np.zeros(6,dtype=int)
k

array([0, 0, 0, 0, 0, 0])

In [65]:
k=np.zeros((3,5))
k

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [67]:
k=np.zeros((2,3),dtype=int)
k

array([[0, 0, 0],
       [0, 0, 0]])

ones() similar to zeros() but returns ones

In [70]:
r=np.ones(3)
r

array([1., 1., 1.])

In [72]:
r=np.ones(3,dtype=int)

In [74]:
r

array([1, 1, 1])

In [76]:
r=np.ones((2,6),dtype=int)
r

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

empty()====Or even an empty array! The function empty creates an array whose initial content is random and depends
on the state of the memory. The reason to use empty over zeros (or something similar) is speed - just make
sure to fill every element afterwards!

In [79]:
np.empty((4,2),dtype=int)

array([[         0,          0],
       [         0, 1072693248],
       [         0, 1073741824],
       [         0, 1074266112]])

In [81]:
np.empty(2,dtype=int)


array([         0, 1072693248])

linspace()=============(to print the numbers between given range on for array)

In [84]:
np.linspace(1,5,3)

array([1., 3., 5.])

In [86]:
np.linspace(2,9,5)

array([2.  , 3.75, 5.5 , 7.25, 9.  ])

identity matrix()

In [89]:
w=np.eye(3,dtype=int)
w

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

random()

In [92]:
q=np.random.rand(2,3)
q

array([[0.71022791, 0.40360863, 0.56644537],
       [0.27357187, 0.52847661, 0.64223017]])

In [94]:
q=np.random.rand(5)
q

array([0.78231626, 0.50270811, 0.46093738, 0.00861749, 0.57130224])

In [96]:
e=np.random.randint(10,20)
e

12

In [98]:
t=np.random.randint(0,9,4)
t

array([6, 7, 6, 1])

In [100]:
r=np.random.randint(10,90,(3,3))
r

array([[88, 59, 50],
       [45, 69, 19],
       [34, 31, 54]])

reshape() size of matrix

In [103]:
e=np.arange(20,50).reshape(10,3)
e

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28],
       [29, 30, 31],
       [32, 33, 34],
       [35, 36, 37],
       [38, 39, 40],
       [41, 42, 43],
       [44, 45, 46],
       [47, 48, 49]])

In [105]:
f=np.random.randint(10,20,(5,2))
f

array([[15, 18],
       [19, 16],
       [12, 17],
       [15, 15],
       [12, 11]])

In [107]:
q=np.arange(10).reshape(5,2)
q

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [109]:
e=np.random.randint(10,50,(10,10))
e

array([[13, 18, 38, 37, 49, 16, 35, 49, 32, 15],
       [14, 32, 41, 12, 14, 48, 14, 39, 22, 36],
       [29, 10, 38, 18, 18, 33, 14, 46, 33, 15],
       [22, 36, 39, 40, 15, 10, 37, 17, 17, 11],
       [42, 19, 19, 49, 25, 15, 32, 36, 42, 40],
       [23, 11, 48, 12, 35, 10, 41, 19, 47, 22],
       [18, 35, 14, 18, 30, 17, 48, 39, 49, 24],
       [42, 21, 37, 10, 17, 34, 19, 40, 14, 34],
       [18, 14, 39, 43, 34, 17, 22, 31, 28, 32],
       [27, 17, 34, 10, 16, 22, 17, 21, 16, 25]])

In [111]:
e[:]

array([[13, 18, 38, 37, 49, 16, 35, 49, 32, 15],
       [14, 32, 41, 12, 14, 48, 14, 39, 22, 36],
       [29, 10, 38, 18, 18, 33, 14, 46, 33, 15],
       [22, 36, 39, 40, 15, 10, 37, 17, 17, 11],
       [42, 19, 19, 49, 25, 15, 32, 36, 42, 40],
       [23, 11, 48, 12, 35, 10, 41, 19, 47, 22],
       [18, 35, 14, 18, 30, 17, 48, 39, 49, 24],
       [42, 21, 37, 10, 17, 34, 19, 40, 14, 34],
       [18, 14, 39, 43, 34, 17, 22, 31, 28, 32],
       [27, 17, 34, 10, 16, 22, 17, 21, 16, 25]])

In [113]:
e[0,0]

13

In [115]:
e[3,3]

40

In [117]:
e[::-1]

array([[27, 17, 34, 10, 16, 22, 17, 21, 16, 25],
       [18, 14, 39, 43, 34, 17, 22, 31, 28, 32],
       [42, 21, 37, 10, 17, 34, 19, 40, 14, 34],
       [18, 35, 14, 18, 30, 17, 48, 39, 49, 24],
       [23, 11, 48, 12, 35, 10, 41, 19, 47, 22],
       [42, 19, 19, 49, 25, 15, 32, 36, 42, 40],
       [22, 36, 39, 40, 15, 10, 37, 17, 17, 11],
       [29, 10, 38, 18, 18, 33, 14, 46, 33, 15],
       [14, 32, 41, 12, 14, 48, 14, 39, 22, 36],
       [13, 18, 38, 37, 49, 16, 35, 49, 32, 15]])

In [119]:
e

array([[13, 18, 38, 37, 49, 16, 35, 49, 32, 15],
       [14, 32, 41, 12, 14, 48, 14, 39, 22, 36],
       [29, 10, 38, 18, 18, 33, 14, 46, 33, 15],
       [22, 36, 39, 40, 15, 10, 37, 17, 17, 11],
       [42, 19, 19, 49, 25, 15, 32, 36, 42, 40],
       [23, 11, 48, 12, 35, 10, 41, 19, 47, 22],
       [18, 35, 14, 18, 30, 17, 48, 39, 49, 24],
       [42, 21, 37, 10, 17, 34, 19, 40, 14, 34],
       [18, 14, 39, 43, 34, 17, 22, 31, 28, 32],
       [27, 17, 34, 10, 16, 22, 17, 21, 16, 25]])

In [121]:
e[0:6:2]

array([[13, 18, 38, 37, 49, 16, 35, 49, 32, 15],
       [29, 10, 38, 18, 18, 33, 14, 46, 33, 15],
       [42, 19, 19, 49, 25, 15, 32, 36, 42, 40]])

In [123]:
e[0:-2:2]

array([[13, 18, 38, 37, 49, 16, 35, 49, 32, 15],
       [29, 10, 38, 18, 18, 33, 14, 46, 33, 15],
       [42, 19, 19, 49, 25, 15, 32, 36, 42, 40],
       [18, 35, 14, 18, 30, 17, 48, 39, 49, 24]])

In [125]:
t=np.random.randint(10,50,10)
t

array([42, 29, 40, 45, 14, 45, 36, 17, 36, 11])

In [127]:
t=np.random.randint(10,100,(5,5))
t

array([[47, 24, 19, 47, 14],
       [50, 21, 81, 50, 34],
       [12, 63, 63, 95, 52],
       [24, 35, 24, 12, 38],
       [50, 31, 13, 97, 70]])

In [129]:
b=np.array([2,3,4,5,6])
b

array([2, 3, 4, 5, 6])

In [131]:
a=np.arange(10,20).reshape(2,5)
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [133]:
b.reshape(5,1)

array([[2],
       [3],
       [4],
       [5],
       [6]])

In [135]:
b.reshape(6,1)

ValueError: cannot reshape array of size 5 into shape (6,1)

In [137]:
c=np.arange(20,30).reshape(2,5)
c

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [139]:
d=np.random.randint(10,40,(6,3))
d

array([[37, 23, 20],
       [23, 12, 10],
       [37, 30, 20],
       [14, 25, 10],
       [11, 33, 19],
       [15, 10, 28]])

In [141]:
arr=np.array([23,24,25,26,27])
arr

array([23, 24, 25, 26, 27])

In [143]:
arr.reshape(5,1)

array([[23],
       [24],
       [25],
       [26],
       [27]])

In [145]:
arr1=np.array([10,20,30,40,50,60,70,80,90,100])
arr1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [147]:
arr1.reshape(5,2)

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [149]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [151]:
mat[4,5]

45

In [153]:
mat[:7]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [155]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [159]:
mat[2:5,4:7]

array([[24, 25, 26],
       [34, 35, 36],
       [44, 45, 46]])

In [161]:
mat[5,4]

54

masking

In [164]:
mat


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [166]:
id(mat)
type(mat)

numpy.ndarray

In [168]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [170]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

BUILT IN FUNCTIONS

ARRAY CREATION FUNCTIONS

In [174]:
a=np.array([1,2,3,45,6])
print(a)

[ 1  2  3 45  6]


In [176]:
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [178]:
c=np.arange(1,11).reshape(2,5)
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# Create an array with linearly spaced values

In [181]:
a=np.linspace(2,10,6)     
#here 6 values are printed from 2 to 10(includimg 2 to 10)
a

array([ 2. ,  3.6,  5.2,  6.8,  8.4, 10. ])

# Create an array filled with zeros

In [184]:
d=np.zeros(5)
d

array([0., 0., 0., 0., 0.])

In [186]:
e=np.zeros((5,2))
e

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [188]:
f=np.zeros((3,3),dtype=int)
f

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Create an array filled with ones

In [191]:
g=np.ones(4)
g

array([1., 1., 1., 1.])

In [193]:
h=np.ones((2,3),dtype=int)
h

array([[1, 1, 1],
       [1, 1, 1]])

# Create an identity matrix

In [196]:
i=np.eye(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [198]:
ARRAY MANIPULATION FUNCTIONS

SyntaxError: invalid syntax (1918014086.py, line 1)

# Reshape an array

In [201]:
j=np.arange(20)
k=np.reshape(j,(5,4))
k

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

# Flatten an array

In [204]:
k=np.array([[1,3,6,7,8],[2,3,4,5,8]])
k

array([[1, 3, 6, 7, 8],
       [2, 3, 4, 5, 8]])

In [206]:
np.ravel(k)


array([1, 3, 6, 7, 8, 2, 3, 4, 5, 8])

# Transpose an array

In [209]:
k

array([[1, 3, 6, 7, 8],
       [2, 3, 4, 5, 8]])

In [211]:
e=np.transpose(k)
e

array([[1, 2],
       [3, 3],
       [6, 4],
       [7, 5],
       [8, 8]])

# Stack arrays vertically

In [214]:
e

array([[1, 2],
       [3, 3],
       [6, 4],
       [7, 5],
       [8, 8]])

In [216]:
np.vstack(e)

array([[1, 2],
       [3, 3],
       [6, 4],
       [7, 5],
       [8, 8]])

MATHEMATICAL FUNCTIONS

In [219]:
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
C=np.add(A,B)
C

array([ 7,  9, 11, 13, 15])

In [221]:
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
d=np.add(B,23)
d

array([29, 30, 31, 32, 33])

# Square each element

In [224]:
print(C)
print(d)

[ 7  9 11 13 15]
[29 30 31 32 33]


In [229]:
k=np.power(C,2)
k

array([ 49,  81, 121, 169, 225], dtype=int32)

In [231]:
k=np.power(d,3)
k

array([24389, 27000, 29791, 32768, 35937], dtype=int32)

# Square root of each element

In [239]:
p=np.array([2,3,4,5,67])
k=np.array([2,3,48,44,22])
o=np.sqrt(p)
o
           

array([1.41421356, 1.73205081, 2.        , 2.23606798, 8.18535277])

dot product size of matrices should be same

In [242]:
print(p)
print(k)

[ 2  3  4  5 67]
[ 2  3 48 44 22]


In [244]:
h=np.dot(p,k)
h

1899

STATISTICAL FUNCTIONS

In [246]:
p

array([ 2,  3,  4,  5, 67])

In [248]:
np.mean(p)

16.2

In [250]:
np.std(p)

25.419677417308034

In [254]:
np.min(p)


2

In [252]:
np.max(p)

67

LINEAR ALGEBRA FUNCTIONS

In [268]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [272]:
b=np.linalg.det(a)
b

-2.0000000000000004

In [276]:
c=np.linalg.inv(a)
c

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
RANDOM SAMPLING FUNCTIONS

In [278]:
a=np.random.rand(5)
a

array([0.12477448, 0.18022888, 0.70247921, 0.42936352, 0.63903698])

In [287]:
np.random.seed(42)
#The number 42 in the above examples is the seed. You can use any integer to control the randomness, and using the 
#same seed will give you the same results each time you run the code.
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

In [289]:
np.random.randint(10,20,5)

array([14, 16, 19, 12, 16])

In [295]:
np.random.randint(10,20,(5,2))

array([[17, 14],
       [13, 17],
       [17, 12],
       [15, 14],
       [11, 17]])

In [ ]:
BOOLEAN AND LOGICAL FUNCTIONS  ALL,ANY

In [297]:
r=np.array([True,True,True])
np.all(r)

True

In [299]:
q=np.array([False,False,True])
np.any(q)

True

set operations

In [301]:
a=np.array([1,2,3,4,5])
b=np.array([21,22,23,24])
np.union1d(a,b)

array([ 1,  2,  3,  4,  5, 21, 22, 23, 24])

In [303]:
np.intersect1d(a,b)

array([], dtype=int32)

In [ ]:
ARRAY ATTRIBUTE FUNCTIONS

In [305]:
q=np.arange(10).reshape(2,5)

In [307]:
q

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [311]:
q.shape

(2, 5)

In [313]:
q.ndim

2

In [315]:
q.size

10

In [317]:
q.dtype

dtype('int32')

In [ ]:
OTHER FUNCTIONS   COPY,BYTES,SHARED FUNCTIONS

In [321]:
A=np.array([23,24])
B=np.copy(A)
B

array([23, 24])

In [327]:
B.nbytes

8

In [329]:
id(A)

2223864038768

In [331]:
id(B)

2223864048944

In [333]:
np.shares_memory(A,B)

False